# =============================================================================
# Database Migrations Configuration
# =============================================================================
# Конфигурация для управления миграциями базы данных
# Используется с Docker Compose и Alembic
# =============================================================================

version: '3.8'

# Сервис для выполнения миграций
services:
  # База данных PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: looseline_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-looseline}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-looseline_secret}
      POSTGRES_DB: ${POSTGRES_DB:-looseline}
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=en_US.UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Инициализационный SQL скрипт
      - ./backend/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-looseline} -d ${POSTGRES_DB:-looseline}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - looseline_network

  # Сервис для выполнения миграций Alembic
  migrations:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: looseline_migrations
    environment:
      # URL подключения к БД
      DATABASE_URL: postgresql://${POSTGRES_USER:-looseline}:${POSTGRES_PASSWORD:-looseline_secret}@db:5432/${POSTGRES_DB:-looseline}
      # Настройки Alembic
      ALEMBIC_CONFIG: alembic.ini
      # Режим выполнения
      MIGRATION_MODE: ${MIGRATION_MODE:-upgrade}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - ./backend/alembic:/app/alembic
      - ./backend/alembic.ini:/app/alembic.ini
    # Команда для выполнения миграций
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        sleep 5 &&
        echo 'Running migrations...' &&
        alembic upgrade head &&
        echo 'Migrations completed successfully!'
      "
    networks:
      - looseline_network
    profiles:
      - migrations

  # Сервис для создания новой миграции
  create_migration:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: looseline_create_migration
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-looseline}:${POSTGRES_PASSWORD:-looseline_secret}@db:5432/${POSTGRES_DB:-looseline}
      MIGRATION_NAME: ${MIGRATION_NAME:-auto_migration}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - ./backend/alembic:/app/alembic
    command: >
      sh -c "
        alembic revision --autogenerate -m '${MIGRATION_NAME:-auto_migration}'
      "
    networks:
      - looseline_network
    profiles:
      - create-migration

  # Сервис для отката миграций
  rollback_migration:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: looseline_rollback
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-looseline}:${POSTGRES_PASSWORD:-looseline_secret}@db:5432/${POSTGRES_DB:-looseline}
      ROLLBACK_STEPS: ${ROLLBACK_STEPS:-1}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - ./backend/alembic:/app/alembic
    command: >
      sh -c "
        alembic downgrade -${ROLLBACK_STEPS:-1}
      "
    networks:
      - looseline_network
    profiles:
      - rollback

  # Сервис для просмотра истории миграций
  migration_history:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: looseline_migration_history
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-looseline}:${POSTGRES_PASSWORD:-looseline_secret}@db:5432/${POSTGRES_DB:-looseline}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - ./backend/alembic:/app/alembic
    command: >
      sh -c "
        echo '=== Migration History ===' &&
        alembic history &&
        echo '' &&
        echo '=== Current Version ===' &&
        alembic current
      "
    networks:
      - looseline_network
    profiles:
      - history

volumes:
  postgres_data:
    driver: local

networks:
  looseline_network:
    driver: bridge

# =============================================================================
# ИСПОЛЬЗОВАНИЕ:
# =============================================================================
#
# 1. Применить все миграции:
#    docker-compose -f migrations.yml --profile migrations up
#
# 2. Создать новую миграцию:
#    MIGRATION_NAME="add_new_table" docker-compose -f migrations.yml --profile create-migration up
#
# 3. Откатить миграцию:
#    ROLLBACK_STEPS=1 docker-compose -f migrations.yml --profile rollback up
#
# 4. Просмотреть историю:
#    docker-compose -f migrations.yml --profile history up
#
# =============================================================================

